services:
  app-blue:
    image: ghcr.io/${ORG_NAME}/spring-api:latest
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/deploy/.env
    volumes:
      - /home/ubuntu/logs:/app/logs
    depends_on:
      - redis
    networks:
      - my-network
    container_name: app-blue

  app-green:
    image: ghcr.io/${ORG_NAME}/spring-api:latest
    ports:
      - "8081:8080"
    env_file:
      - /home/ubuntu/deploy/.env
    volumes:
      - /home/ubuntu/logs:/app/logs
    depends_on:
      - redis
    networks:
      - my-network
    container_name: app-green

  redis:
    image: redis:7.4.1
    restart: always
    volumes:
      - /home/ubuntu/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - /home/ubuntu/redis/redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - my-network
    container_name: redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/deploy/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    depends_on:
      - app-blue
      - app-green
    networks:
      - my-network
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /home/ubuntu/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - my-network

  frontend:
    image: ghcr.io/${ORG_NAME}/frontend:latest
    container_name: frontend
    restart: always
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - /home/ubuntu/deploy/.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - my-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - my-network

  pushgateway:
    image: prom/pushgateway
    container_name: 'pushgateway'
    ports:
      - '9091:9091'
    networks:
      - my-network

volumes:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  my-network:
    driver: bridge
